#!/bin/bash

COMMAND=$1

parse_yaml() {
	local prefix=$2
	local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
	sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
			-e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
	awk -F$fs '{
		indent = length($1)/2;
		vname[indent] = $2;
		for (i in vname) {if (i > indent) {delete vname[i]}}
		if (length($3) > 0) {
			vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
			printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
		}
	}'
}

echo_bold() {
	local bold=$(tput bold)
	local normal=$(tput sgr0)
	echo -n $bold
	echo "$@"
	echo -n $normal
}

if [[ $COMMAND == "update-db" ]]; then
	if [ -f secrets/.passwords.yml ]; then
eval $(parse_yaml "secrets/.passwords.yml")
	else
		echo "Mot de passe MySQL (dev) ?"
		read -s passwords_dev_mysql
		echo "Mot de passe MySQL (prod) ?"
		read -s passwords_prod_mysql
	fi

	echo_bold "Dropping dev database"
	mysql --password="$passwords_dev_mysql" -e "DROP DATABASE wordpress"
	echo_bold -e "\xE2\x9C\x94 DONE!"

	echo_bold "Loading database from prod..."
	mysqldump -h 52.31.221.186 -u ubuntu wordpress --databases --password="$passwords_prod_mysql" | mysql --password="$passwords_dev_mysql"
	echo_bold -e "\xE2\x9C\x94 DONE!"

	exit 0;
fi

echo "Command \"$COMMAND\" not found." 1>&2
exit 1;
