---
- hosts: prod
  become: yes
  vars_files:
    - ../secrets/.passwords.yml
    - vars/base.yml
    - vars/prod.yml
  roles:
    - common
    - php
    - node
    - nginx
    - mysql
    - wordpress
