---
- name: Clone project
  git:
    repo: git://github.com/KennyDurand/blog-voyage.git
    dest: /var/www/blog-voyage
    version: master
    force: yes
    accept_hostkey: yes
  when: environment_name != 'dev'

- name: Create environment file
  template:
    src: .env.dist
    dest: /var/www/blog-voyage/.env.{{ environment_name }}
  when: environment_name != 'dev'

- name: Run Composer
  shell: composer install -n
  args:
    chdir: /var/www/blog-voyage

- name: Create database
  mysql_db:
    name: wordpress
    config_file: ../secrets/.root.cnf

- name: Create user
  mysql_user:
    name: ubuntu
    password: "{{ mysql.password }}"
    priv: 'wordpress.*:ALL'
    config_file: ../secrets/.root.cnf

- name: Allow access from outside
  mysql_user:
    name: ubuntu
    password: "{{ mysql.password }}"
    priv: 'wordpress.*:ALL'
    host_all: yes
    config_file: ../secrets/.root.cnf

- include: deploy.yml
